### ISSUE TITLE
Adicionar validação para tipos Long

### ISSUE THREAD

**Issue by Kerooker** [Kerooker/SimpleCpfValidator#2]
CPFs cabem e também podem ser registrados em tipos `Long`. É interessante ter uma validação para isso também

**Comment by rmxsantiago** [comment]
Posso trabalhar nessa issue.

**Comment by rmxsantiago** [comment]
Pelo que entendi, você quer que além de String, também seja possível Long ser validado como CPF. 
Você pode esclarecer?

**Comment by Kerooker** [comment]
Exatamente.

CPFs cabem dentro de longs, então por exemplo:
`val longCpf: Long = 99999999999`
é um CPF que não dá overflow.

Eu acredito ser válido fazer isso:
`longCpf.isCpf()`

Uma sugestão de implementação seria simplesmente criar um overload da função `String.isCpf` para `Long.isCpf`, e chamar o primeiro via `toString()`.

No entanto, algo que deve ser observado: Deve ser permitido passar um long negativo? Isso levaria a uma string com `-` no começo. Deixo para você tomar uma decisão quanto a isso!
