### ISSUE TITLE
Colocar license no cabeçalho de todos os arquivos

### ISSUE THREAD

**Issue by Kerooker** [Kerooker/SimpleCpfValidator#3]

**Comment by rmxsantiago** [comment]
Posso trabalhar nessa issue.

**Comment by Kerooker** [comment]
É toda sua!

**Comment by rmxsantiago** [comment]
Preciso só copiar o conteúdo do LICENSE colocando teu nome e o ano 2019 e sair colando como comentário em todos os arquivos de código. É isso mesmo?

**Comment by Kerooker** [comment]
Acho que o mais correto seria colocar apenas nos arquivos fonte!

**Comment by rmxsantiago** [comment]
Me expressei mal. arquivos de código, quis dizer código fonte. Quer que coloque nos arquivos de build tbm (.kts)?

**Comment by Kerooker** [comment]
Acho que o correto seria colocar em todo arquivo fonte apenas.

No final da LICENSE file há um guia de como aplicar a license. Acho que o correto não é copiar 100% do arquivo não
